sequenceDiagram
    participant browser
    participant server

      Note right of browser: When user enters input and clicks "Save" button:
      browser ->> server : POST REQUEST TO ADDRESS "https://studies.cs.helsinki.fi/exampleapp/new_note"
      Note right of browser: the POST request contains the user input in the payload
      server -->> browser : redirect to address "/exampleapp/notes"
      browser ->> server : GET REQUEST to same address "/exampleapp/notes"
      Note right of browser: the browser reloads the whole page now updated with new note

