sequenceDiagram
    participant browser
    participant server
 
   browser->> server : POST https://studies.cs.helsinki.fi/exampleapp/new_note
   server -->> browser: GET /exampleapp/notes
   Note right of browser: the browser reloads the page

   browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    server-->>browser: HTML document

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    note left of server: the JavaScript file is executed and the JSON file is fetched with updated notes
  
